### ISSUE TITLE
Check if a refresh db entry exists on get

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/levelup-cache#3]
Whenever a get happens, this should check if a `refresh` database entry exists, and create it if it does not.

Depends on https://github.com/TehShrike/expire-unused-keys/issues/6 and https://github.com/TehShrike/expire-unused-keys/issues/7.

**Comment by TehShrike** [comment]
1. levelup-cache should switch to calling expire-unused-keys with an options object with `repeatExpirations: true`
2. to fix issues caused by previous bugs, `refreshTimestamps.createIfNotExists(key)` should be called at least in here https://github.com/TehShrike/levelup-cache/blob/master/index.js#L103 but maybe just in the expiration callback here https://github.com/TehShrike/levelup-cache/blob/master/index.js#L90
